name: Tickets Watcher

on:
  schedule:
    - cron: "*/15 * * * *"   # ogni 5 minuti
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i

      # Installa Chromium + dipendenze di sistema per Playwright
      - run: npx playwright install --with-deps chromium

      - name: Scrape & POST
        run: npm run scrape
